### ISSUE TITLE
Cannot see slicer anymore in installed plugins.

### ISSUE THREAD

**Issue by GuinnessDublin** [OctoPrint/OctoPrint-Slic3r#21]
First got problem,  could not upload more slic3r profiles. Deleted couple, still bo luck. After that uninstalled slic3r. And installed it again. Now i cannot see it in installed plugins. Bur can use it, but still cannot export more profiles to it. 

Any help to this?

**Comment by fromagek** [comment]
Try if you can find slic3r in browser private mode or using a different browser.
I had problems with the cache in firefox.

**Comment by GuinnessDublin** [comment]
Yes clearing cache did help. Thank you. All good now :) And i could export new profile also to slic3r :)

**Comment by eyal0** [comment]
Sounds like it's working now.  Glad to hear it.
