### ISSUE TITLE
Slic3r not in Slicer selector

### ISSUE THREAD

**Issue by shguro** [OctoPrint/OctoPrint-Slic3r#22]
Hi,
i have installed the Slic3r and the Plugin on my PI but the Slic3r will not be shown in the Slicer selector.

Thanks for Help

**Comment by eyal0** [comment]
Can you explain more?  Maybe a screenshot?

**Comment by leobel96** [comment]
I had the same issue
![cattura](https://user-images.githubusercontent.com/19806799/28966517-f2a62b04-7916-11e7-8127-7d011b3ca828.PNG) I resolved disabling cura slicer from plugin manager and rebooting raspberry

**Comment by eyal0** [comment]
This can happen if the directory that you put for OctoPrint-Slic3r is wrong.

Is it working for you now?

**Comment by leobel96** [comment]
The directory was correct. I resolved disabling cura slicer

**Comment by eyal0** [comment]
That's strange.  You should not need to disable cura for slic3r to work.  They should be able to work together.

If you are satisfied, I will close this issue.
