### ISSUE TITLE
Profile description

### ISSUE THREAD

**Issue by Passaita** [OctoPrint/OctoPrint-Slic3r#25]
I have successfully installed and tested this plugin with Slic3r 1.33.8. Versions with TBB on RPI. Great job!
Is it possible to add more descriptive profile description field?
Having multiple profiles with different variables not just filament (i.e. Infill, skirt, brim, support, speed and etc.) will become confusing at some point as the name of profile won't fit enough information.

As an alternative solution and more difficult to implement: having control over some of these option through the web interface would be extremely beneficial.

**Comment by eyal0** [comment]
This is the same as https://github.com/OctoPrint/OctoPrint-Slic3r/issues/24 .

I suggest that you get the Slicer plugin for octoprint.  It will let you set all the options that you've named in addition to letting you rotate the object, scale it, and put multiple on the platform.

You can get it here: http://plugins.octoprint.org/plugins/slicer/

**Comment by Passaita** [comment]
Awesome! Thank you. Missed this plugin.
