### ISSUE TITLE
Accessing config bundles

### ISSUE THREAD

**Issue by theDrsh** [OctoPrint/OctoPrint-Slic3r#26]
Within Prusa slic3r there is a config bundle, which holds settings which allow you to choose layer height, and material, on the fly. It would be nice to have the same interface within the octoprint slic3r.

**Comment by eyal0** [comment]
Have you tried [OctoPrint-Slicer](http://plugins.octoprint.org/plugins/slicer/)?  I think that it will do what you want.

**Comment by eyal0** [comment]
Too long without a response.  I'm closing this.  Re-open if you need a better solution.
