### ISSUE TITLE
can't post a request, this is not an issue but a request

### ISSUE THREAD

**Issue by cnlson** [OctoPrint/OctoPrint-Slic3r#27]
is there any way to make this pull slic3r prusa edition?

https://github.com/prusa3d/Slic3r

**Comment by eyal0** [comment]
Did you try the instructions?

https://github.com/OctoPrint/OctoPrint-Slic3r/wiki/How-to-install-Slic3r-on-RPi

**Comment by cnlson** [comment]
I'm looking to put a different slic3r, the prusa edition that has a
different git than the standard slic3r

**Comment by eyal0** [comment]
I understand.  In the instructions, it explains how to put the prusa edition.  Did you try that?

**Comment by eyal0** [comment]
It's been too long without an answer.  I'm closing this.  Re-open if you're still having trouble.
