### ISSUE TITLE
Add more fan options

### ISSUE THREAD

**Issue by leobel96** [OctoPrint/OctoPrint-Slic3r#29]
Please add the possibility to disable the fan for the first "X" layers to make first layers better stuck on the bed

**Comment by eyal0** [comment]
You need to upload a config that has that option.

Are you using OctoPrint-Slicer (with an "e") in addition to OctoPrint-Slic3r (with a "3")?  The former is the one with a graphical interface and the ability to override settings.

**Comment by leobel96** [comment]
Damn, I have confused the two plugins. I'll open this issue on the right one. Thank you!
