### ISSUE TITLE
Cannot install Slic3r - stuck on step 2

### ISSUE THREAD

**Issue by ccampolo** [OctoPrint/OctoPrint-Slic3r#32]
Unfortunately I have very little knowledge of Raspberry Pi and I am trying to install slic3r to use with my OctoPi Setup.
After increasing the swap size, I copied and pasted the text (as stated in the guide)

`SLIC3R_REPO="https://github.com/alexrj/Slic3r.git
SLIC3R_VERSION="master"
SLIC3R_DIR=~/Slic3r`

Although when I press enter nothing happens.
Do you know how can I fix this?

**Comment by alexiri** [comment]
I think you're missing some newlines, those should be three commands. Anyway, those commands just define variables, so you won't see any output. You need to keep going.

**Comment by ccampolo** [comment]
Okay sorry, my bad.
I was expecting some sort of output after those lines. Managed to do everything - Thanks!
