### ISSUE TITLE
Can't get Slic3r PE 1.41.3 to compile

### ISSUE THREAD

**Issue by NovaViper** [OctoPrint/OctoPrint-Slic3r#44]
I'm having major issues trying to install Slic3r PE v1.41.3. I get as far as to `sudo make -j2`, then it starts spitting back errors such as this one: https://pastebin.com/au0nfWiT

Here are the configurations I used: https://pastebin.com/Pt5EM1YY

I'm completely lost as to what to do, because I can get version 1.39.2 to compile just fine.

**Comment by Goodfeat** [comment]
How did you compile 1.41.3?
I can't do it
The program requires the WxWidgets 3 library.
Error 255 is related to the config.ini file. I managed to get rid of this error on 1.39.2 by loading the configuration from the previous version of the slicer

**Comment by NovaViper** [comment]
> How did you compile 1.41.3?
> I can't do it
> The program requires the WxWidgets 3 library.
> Error 255 is related to the config.ini file. I managed to get rid of this error on 1.39.2 by loading the configuration from the previous version of the slicer

I **didn't** get it to compile on 1.41.3, but got it to compile on 1.39.2

**Comment by roboknight** [comment]
It's now on the Wiki, but there are a few things:
1) you can get rid of WxWidgets dependencies.  Edit the CMakeLists.txt file and comment out lines 26 and 28.  They are WxWidgets and GL related.  Unless you plan on using a monitor with OctoPi and doing slicing that way, you won't need them.
2) You won't be able to build it with the given Boost library.  rPi currently only has 1.62.  1.64 is needed at least.

**Comment by NovaViper** [comment]
I'll give it try when I get home this weekend

**Comment by roboknight** [comment]
So, I tried it.  The code still ends up with wxWidgets dependencies, even when I turn OFF the GUI in the options.  I'm working on a fix now, but it takes forever to finish compiling.

**Comment by NovaViper** [comment]
Has the beta versions of 1.42 been tested yet? I started using that build because of the support for sequential printing

**Comment by roboknight** [comment]
Well, I finally got it built... Probably hasn't really been tested enough, but it had some features I wanted to try out.  However, it won't work with OctoPrint just yet because instead of -print-center, its option is now just -center... Causes OctoPrint-Slic3r to barf for now.  But if you want to build it, I posted some info under one of the other issues.  Funny thing is, I actually started wanting to build 1.41.3, but looks like I ended up with 1.42.0-beta.

**Comment by roboknight** [comment]
Okay, so you might want to check: #47

That is how I finally got things built.

**Comment by eyal0** [comment]
> Well, I finally got it built... Probably hasn't really been tested enough, but it had some features I wanted to try out. However, it won't work with OctoPrint just yet because instead of -print-center, its option is now just -center... Causes OctoPrint-Slic3r to barf for now. But if you want to build it, I posted some info under one of the other issues. Funny thing is, I actually started wanting to build 1.41.3, but looks like I ended up with 1.42.0-beta.

I think that I fixed the `--print-center` vs `--center` thing already.
