### ISSUE TITLE
Slic3r Prusa Edition 1.42.0-beta

### ISSUE THREAD

**Issue by roboknight** [OctoPrint/OctoPrint-Slic3r#48]
It appears the command --print-center is now just --center x,y

**Comment by roboknight** [comment]
So on line 280 of __init__.py, I had to do the following to get slic3r-gui to work:
```
                args = ['"%s"' % executable, '--slice', '--load', '"%s"' % profile_path, '--center', '"%f,%f"' % (posX, posY), '-o', '"%s"' % machinecode_path, '"%s"' % model_path]
```
I had to add the --slice option, and --print-center changed to --center.  But it seems my configuration file worked okay.  I sliced my first file with OctoPrint and Slic3r PE 1.42.0-beta.

**Comment by eyal0** [comment]
It will be hard to keep track of all the different flags that Slic3r has and changes. 😞

**Comment by eyal0** [comment]
I think that I fixed this already.  Please check again.
