### ISSUE TITLE
Have any currently open issues been resolved?

### ISSUE THREAD

**Issue by oliverhbailey** [OctoPrint/OctoPrint-Slic3r#65]
Looking at this thread, if there these open issues haven't been resolved, Slic3r isn't going to build. You have libraries that are out of date and don't appear to have been rebuilt or updated. The only way to get the non Prusa specific version of Slic3r to build with Octopi is to fix the outstanding issues, oldest first so the current 1.3.0 version can be built. The version currently on Windows is 1.3.0 and the Pi version needs to match that version number. And speaking of version number, it doesn't look like Slic3r 1.29 has been built either, so the latest version won't build until that version is working.

**Comment by eyal0** [comment]
I've given up on compiling slic3r on Pi.  It was always a pain!  Using the AppImage from prusa was a million times easier.

Maybe someone has made a slic3r AppImage?  That would be great!
